// server/src/client/src/pages/AlbumList.svelte
<script lang="ts">
    import { onMount } from "svelte";

    import AlbumDetail from "./AlbumDetail.svelte";
    import SubPage from "../components/SubPage.svelte";
    import AlbumListItem from "../components/AlbumListItem.svelte";
    import Sort from "../icons/Sort.svelte";

    import { useGradualRender } from "../hooks/useGradualRender";

    import { albums, albumSortPanel } from "../store";

    let selectedId: string | null = null;
    let isOpenDetail = false;

    let search = "";
    let innerAlbums = useGradualRender($albums, 40);

    onMount(() => {
        albums.subscribe((albums) => {
            $innerAlbums = albums;
        });
    });

    $: visibleAlbums = $innerAlbums.filter(
        (album) =>
            search === "" ||
            album.name.toLowerCase().includes(search.toLowerCase()) ||
            album.artist.name.toLowerCase().includes(search.toLowerCase())
    );
</script>

<div class="controls">
    <div>
        <input
            class="gray-input"
            type="text"
            placeholder="Search"
            bind:value={search}
        />
    </div>
    <div class="buttons">
        <button
            class="gray-button"
            on:click={() => ($albumSortPanel.isOpen = true)}
        >
            <Sort />
        </button>
    </div>
</div>
<div class="grid">
    {#each visibleAlbums as album}
        <AlbumListItem
            onClick={() => {
                selectedId = album.id;
                isOpenDetail = true;
            }}
            albumName={album.name}
            albumCover={album.cover}
            artistName={album.artist.name}
        />
    {/each}
</div>

<SubPage
    isOpen={isOpenDetail}
    onClose={() => {
        selectedId = null;
        isOpenDetail = false;
    }}
>
    {#if selectedId}
        <AlbumDetail id={selectedId} />
    {/if}
</SubPage>

<style lang="scss">
    .grid {
        display: grid;
        grid-gap: 1rem;
        grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
        padding: 1rem;
        list-style: none;

        @media (max-width: 600px) {
            grid-template-columns: repeat(2, minmax(0, 1fr));
        }
    }
</style>

// server/src/client/src/pages/AlbumList.tsx
import { prompt } from '@baejino/ui'
import styled from '@emotion/styled'
import { useStore } from 'badland-react'
import { useState } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'

import { AlbumItem, Loading, Observer, SecondaryButton, StickyHeader } from '~/components'

import { albumStore } from '~/store/album'

const Grid = styled.div`
    display: grid;
    grid-gap: 1rem;
    grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
    padding: 1rem;
    list-style: none;

    @media (max-width: 600px) {
        grid-template-columns: repeat(2, minmax(0, 1fr));
    }
`

const RENDER_LIMIT = 100

export default function Album() {
    const navigate = useNavigate()
    const [searchParams, setSearchParams] = useSearchParams()

    const [{ albums, loaded }] = useStore(albumStore)
    const [renderLimit, setRenderLimit] = useState(Number(searchParams.get('l')) || RENDER_LIMIT)

    const handleSearch = async () => {
        const q = await prompt('Search keyword', searchParams.get('q') || '')
        setSearchParams({ q })
    }

    const filteredAlbums = albums
        ?.filter(album =>
            album.name.toLowerCase().includes(searchParams.get('q')?.toLowerCase() || '') ||
            album.artist.name.toLowerCase().includes(searchParams.get('q')?.toLowerCase() || '')
        )

    return (
        <>
            <StickyHeader>
                <SecondaryButton style={{ width: '160px' }} onClick={handleSearch}>
                    {searchParams.get('q') || 'Search'}
                </SecondaryButton>
            </StickyHeader>
            {!loaded && (
                <Loading />
            )}
            <Grid>
                {loaded && filteredAlbums.slice(0, renderLimit).map((album) => (
                    <AlbumItem
                        key={album.id}
                        albumName={album.name}
                        albumCover={album.cover}
                        artistName={album.artist.name}
                        onClick={() => navigate(`/album/${album.id}`)}
                    />
                ))}
            </Grid>
            {loaded && filteredAlbums.length > renderLimit && (
                <Observer onIntersect={() => {
                    setRenderLimit(renderLimit + RENDER_LIMIT)
                    searchParams.set('l', (renderLimit + RENDER_LIMIT).toString())
                    setSearchParams(searchParams, { replace: true })
                }} />
            )}
        </>
    )
}
