// server/src/client/src/pages/ArtistDetail.svelte
<script lang="ts">
    import { onMount } from "svelte";

    import AlbumDetail from "./AlbumDetail.svelte";
    import Image from "../components/Image.svelte";
    import SubPage from "../components/SubPage.svelte";
    import MusicListItem from "../components/MusicListItem.svelte";
    import AlbumListItem from "../components/AlbumListItem.svelte";
    import Play from "../icons/Play.svelte";

    import type { Artist } from "../models/type";

    import { getArtist } from "../api";

    import {
        existQueue,
        insertToQueue,
        musicActionPanel,
        musics,
        resetQueue,
    } from "../store";

    export let id = "";

    let artist: Artist = null;
    let selectedAlbumId: string | null = null;
    let isOpenAlbumDetail = false;

    onMount(async () => {
        musics.subscribe((value) => {
            if (artist) {
                artist.musics = artist.musics.map((music) => {
                    music.isLiked = value.find(
                        (m) => m.id === music.id
                    )?.isLiked;
                    return music;
                });
            }
        });
    });

    $: if (id) {
        getArtist(id).then(({ data }) => {
            artist = data.artist;
        });
    }
</script>

<section>
    {#if artist}
        <div class="artist-name">
            <Image src={artist.latestAlbum?.cover || ""} alt={artist.name} />
            {artist.name}
        </div>

        <div class="section-title">
            Albums ({artist.albums.length})
        </div>
        <div class="albums">
            <ul>
                {#each artist.albums as album}
                    <li>
                        <AlbumListItem
                            albumCover={album.cover}
                            albumName={album.name}
                            artistName={album.publishedYear}
                            onClick={() => {
                                selectedAlbumId = album.id;
                                isOpenAlbumDetail = true;
                            }}
                        />
                    </li>
                {/each}
            </ul>
        </div>

        <div class="section-title">
            Songs ({artist.musics.length})
            <div class="play-all">
                <button
                    class="gray-button"
                    on:click={() =>
                        resetQueue(
                            `Play music by ${artist.name}`,
                            artist.musics
                        )}
                >
                    <Play />
                    Play
                </button>
            </div>
        </div>
        <div class="musics">
            <ul>
                {#each artist.musics as music}
                    <li>
                        <MusicListItem
                            artistName={music.album.name}
                            albumCover={music.album.cover}
                            albumName={music.album.name}
                            musicName={music.name}
                            musicCodec={music.codec}
                            isLiked={music.isLiked}
                            onClick={() => insertToQueue(music)}
                            onLongPress={() => {
                                musicActionPanel.update((state) => ({
                                    ...state,
                                    isOpen: true,
                                    music,
                                }));
                            }}
                        />
                    </li>
                {/each}
            </ul>
        </div>
    {/if}
</section>

<SubPage
    isOpen={isOpenAlbumDetail}
    onClose={() => {
        selectedAlbumId = null;
        isOpenAlbumDetail = false;
    }}
>
    {#if selectedAlbumId}
        <AlbumDetail id={String(selectedAlbumId)} />
    {/if}
</SubPage>

<style lang="scss">
    section {
        .artist-name {
            display: flex;
            flex-direction: column;
            align-items: center;
            font-size: 1.25rem;
            font-weight: bold;
            margin: 3rem 0;

            :global(img) {
                width: 150px;
                height: 150px;
                object-fit: cover;
                border-radius: 50%;
                margin-bottom: 1rem;
            }
        }

        .section-title {
            padding: 1rem;
            font-size: 1.25rem;
            font-weight: bold;
            border-bottom: 1px solid #222;
            display: flex;
            align-items: center;
            justify-content: space-between;
        }

        .albums {
            padding: 0 1rem 1rem 1rem;
            margin-bottom: 3rem;

            ul {
                display: grid;
                grid-gap: 1rem;
                grid-template-columns: repeat(auto-fill, minmax(160px, 1fr));
                padding: 0;
                list-style: none;

                @media (max-width: 600px) {
                    grid-template-columns: repeat(2, minmax(0, 1fr));
                }
            }
        }

        .musics {
            ul {
                margin: 0;
                padding: 0;
                list-style: none;
            }
        }

        .play-all {
            display: flex;
            align-items: center;
            justify-content: space-between;
            gap: 0.75rem;
        }
    }
</style>

// server/src/client/src/pages/ArtistDetail.tsx
import styled from '@emotion/styled'
import { useStore } from 'badland-react'
import { useQuery } from 'react-query'
import { useNavigate, useParams } from 'react-router-dom'

import { AlbumItem, Image, MusicActionPanelContent, MusicItem, SecondaryButton } from '~/components'
import { Play } from '~/icon'

import { getArtist } from '~/api'

import { musicStore } from '~/store/music'
import { queueStore } from '~/store/queue'
import { panel } from '~/modules/panel'

const Container = styled.section`
    .artist-name {
        display: flex;
        flex-direction: column;
        align-items: center;
        font-size: 1.25rem;
        font-weight: bold;
        margin: 3rem 0;

        img {
            width: 150px;
            height: 150px;
            object-fit: cover;
            border-radius: 50%;
            margin-bottom: 1rem;
        }
    }

    .section-title {
        padding: 1rem;
        font-size: 1.25rem;
        font-weight: bold;
        border-bottom: 1px solid #222;
        display: flex;
        align-items: center;
        justify-content: space-between;
    }

    .albums {
        padding: 1rem;
        margin-bottom: 3rem;
        display: grid;
        grid-gap: 1rem;
        grid-template-columns: repeat(auto-fill, minmax(160px, 1fr));

        @media (max-width: 600px) {
            grid-template-columns: repeat(2, minmax(0, 1fr));
        }
    }

    .musics {
        margin: 0;
        padding: 0;
        list-style: none;
    }
`

export default function ArtistDetail() {
    const navigate = useNavigate()

    const { id } = useParams<{ id: string }>()

    const { data: artist } = useQuery(['album', id], () => getArtist(id!).then(res => res.data.artist), {
        enabled: !!id,
    })

    const [{ musicMap }] = useStore(musicStore)

    if (!artist) {
        return null
    }

    return (
        <Container>
            <div className="artist-name">
                <Image src={artist.latestAlbum?.cover || ''} alt={artist.name} />
                {artist.name}
            </div>
            <div className="section-title">
                Albums ({artist.albums.length})
            </div>
            <div className="albums">
                {artist.albums.map(album => (
                    <AlbumItem
                        key={album.id}
                        albumCover={album.cover}
                        albumName={album.name}
                        artistName={album.publishedYear}
                        onClick={() => navigate(`/album/${album.id}`)}
                    />
                ))}
            </div>

            <div className="section-title">
                Songs ({artist.musics.length})
                <SecondaryButton onClick={() => queueStore.reset(artist.musics.map(music => music.id))}>
                    <Play /> Play
                </SecondaryButton>
            </div>
            <div className="musics">
                {artist.musics.map(({ id }) => {
                    const music = musicMap.get(id)

                    if (!music) return null

                    return (
                        <MusicItem
                            key={music.id}
                            artistName={music.album.name}
                            albumCover={music.album.cover}
                            albumName={music.album.name}
                            musicName={music.name}
                            musicCodec={music.codec}
                            isLiked={music.isLiked}
                            onClick={() => queueStore.add(music.id)}
                            onLongPress={() => panel.open({
                                content: (
                                    <MusicActionPanelContent
                                        id={music.id}
                                        onAlbumClick={() => navigate(`/album/${music.album.id}`)}
                                        onArtistClick={() => navigate(`/artist/${music.artist.id}`)}
                                    />
                                )
                            })}
                        />
                    )
                })}
            </div>
        </Container>
    )
}
