// packages/client/src/pages/ArtistDetail.tsx
import { useAppStore as useStore } from '~/store/base-store';
import { useQuery } from '@tanstack/react-query';
import { useNavigate, useParams } from 'react-router-dom';

import { AlbumListItem } from '~/components/album';
import { ArtistSummary } from '~/components/artist';
import { TwoToneLayout } from '~/components/layout';
import { MusicActionPanelContent, MusicListItem } from '~/components/music';
import { Text } from '~/components/shared';
import { Play } from '~/icon';

import { getArtist } from '~/api';
import { queryKeys } from '~/api/query-keys';

import { musicStore } from '~/store/music';
import { queueStore } from '~/store/queue';
import { panel } from '~/modules/panel';
import { useResetQueue } from '~/hooks';

export default function ArtistDetail() {
    const navigate = useNavigate();
    const resetQueue = useResetQueue();

    const { id } = useParams<{ id: string }>();

    const { data: artist } = useQuery({
        queryKey: queryKeys.artists.detail(id),
        queryFn: async () => {
            const { data } = await getArtist(id!);
            return data.artist;
        },
        enabled: !!id
    });

    const [{ musicMap }] = useStore(musicStore);

    if (!artist) {
        return null;
    }

    const listenedCount = artist.musics.reduce((acc, { id }) => acc += musicMap.get(id)?.playCount || 0, 0);

    return (
        <TwoToneLayout
            backgroundImage={artist.latestAlbum?.cover || ''}
            header={(
                <ArtistSummary
                    name={artist.name}
                    cover={artist.latestAlbum?.cover || ''}
                    listenedCount={listenedCount}
                />
            )}
            primaryAction={(
                <button onClick={() => void resetQueue(artist.musics.map(music => music.id))}>
                    <Play />
                </button>
            )}>
            <div className="mb-[var(--b-spacing-2xl)] last:mb-0">
                <div className="mb-[var(--b-spacing-sm)] flex items-center justify-between gap-[var(--b-spacing-md)] px-[var(--b-spacing-lg)] py-[var(--b-spacing-md)]">
                    <div className="flex items-center gap-[var(--b-spacing-sm)]">
                        <Text as="h2" size="xl" weight="semibold">
                            Albums
                        </Text>
                        <Text variant="tertiary" size="sm">
                            {artist.albums.length}
                        </Text>
                    </div>
                </div>
                <div className="overflow-x-auto px-[var(--b-spacing-lg)] pb-[var(--b-spacing-sm)] [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">
                    <div className="grid w-max auto-cols-[minmax(240px,320px)] grid-flow-col gap-[var(--b-spacing-sm)] [scroll-snap-type:x_proximity]">
                        {artist.albums.map(album => (
                            <div key={album.id} className="min-w-0 overflow-hidden rounded-[var(--b-radius-lg)] border border-[var(--b-color-border-subtle)] bg-transparent [scroll-snap-align:start]">
                                <AlbumListItem
                                    albumCover={album.cover}
                                    albumName={album.name}
                                    artistName={artist.name}
                                    publishedYear={album.publishedYear}
                                    musicCount={album.musics?.length}
                                    compact
                                    onClick={() => navigate(`/album/${album.id}`)}
                                />
                            </div>
                        ))}
                    </div>
                </div>
            </div>

            <div className="mb-[var(--b-spacing-2xl)] last:mb-0">
                <div className="mb-[var(--b-spacing-sm)] flex items-center justify-between gap-[var(--b-spacing-md)] px-[var(--b-spacing-lg)] py-[var(--b-spacing-md)]">
                    <div className="flex items-center gap-[var(--b-spacing-sm)]">
                        <Text as="h2" size="xl" weight="semibold">
                            Songs
                        </Text>
                        <Text variant="tertiary" size="sm">
                            {artist.musics.length}
                        </Text>
                    </div>
                </div>
                <div className="flex flex-col">
                    {artist.musics.map(({ id }) => {
                        const music = musicMap.get(id);

                        if (!music) return null;

                        return (
                            <MusicListItem
                                key={music.id}
                                artistName={music.artist.name}
                                albumCover={music.album.cover}
                                albumName={music.album.name}
                                musicName={music.name}
                                musicCodec={music.codec}
                                isLiked={music.isLiked}
                                isHated={music.isHated}
                                onClick={() => queueStore.add(music.id)}
                                onLongPress={() => panel.open({
                                    title: 'Related to this music',
                                    content: (
                                        <MusicActionPanelContent
                                            id={music.id}
                                            onAlbumClick={() => navigate(`/album/${music.album.id}`)}
                                        />
                                    )
                                })}
                            />
                        );
                    })}
                </div>
            </div>
        </TwoToneLayout>
    );
}

// server/src/client/src/pages/ArtistDetail.svelte
<script lang="ts">
    import { onMount } from "svelte";

    import AlbumDetail from "./AlbumDetail.svelte";
    import Image from "../components/Image.svelte";
    import SubPage from "../components/SubPage.svelte";
    import MusicListItem from "../components/MusicListItem.svelte";
    import AlbumListItem from "../components/AlbumListItem.svelte";
    import Play from "../icons/Play.svelte";

    import type { Artist } from "../models/type";

    import { getArtist } from "../api";

    import {
        existQueue,
        insertToQueue,
        musicActionPanel,
        musics,
        resetQueue,
    } from "../store";

    export let id = "";

    let artist: Artist = null;
    let selectedAlbumId: string | null = null;
    let isOpenAlbumDetail = false;

    onMount(async () => {
        musics.subscribe((value) => {
            if (artist) {
                artist.musics = artist.musics.map((music) => {
                    music.isLiked = value.find(
                        (m) => m.id === music.id
                    )?.isLiked;
                    return music;
                });
            }
        });
    });

    $: if (id) {
        getArtist(id).then(({ data }) => {
            artist = data.artist;
        });
    }
</script>

<section>
    {#if artist}
        <div class="artist-name">
            <Image src={artist.latestAlbum?.cover || ""} alt={artist.name} />
            {artist.name}
        </div>

        <div class="section-title">
            Albums ({artist.albums.length})
        </div>
        <div class="albums">
            <ul>
                {#each artist.albums as album}
                    <li>
                        <AlbumListItem
                            albumCover={album.cover}
                            albumName={album.name}
                            artistName={album.publishedYear}
                            onClick={() => {
                                selectedAlbumId = album.id;
                                isOpenAlbumDetail = true;
                            }}
                        />
                    </li>
                {/each}
            </ul>
        </div>

        <div class="section-title">
            Songs ({artist.musics.length})
            <div class="play-all">
                <button
                    class="gray-button"
                    on:click={() =>
                        resetQueue(
                            `Play music by ${artist.name}`,
                            artist.musics
                        )}
                >
                    <Play />
                    Play
                </button>
            </div>
        </div>
        <div class="musics">
            <ul>
                {#each artist.musics as music}
                    <li>
                        <MusicListItem
                            artistName={music.album.name}
                            albumCover={music.album.cover}
                            albumName={music.album.name}
                            musicName={music.name}
                            musicCodec={music.codec}
                            isLiked={music.isLiked}
                            onClick={() => insertToQueue(music)}
                            onLongPress={() => {
                                musicActionPanel.update((state) => ({
                                    ...state,
                                    isOpen: true,
                                    music,
                                }));
                            }}
                        />
                    </li>
                {/each}
            </ul>
        </div>
    {/if}
</section>

<SubPage
    isOpen={isOpenAlbumDetail}
    onClose={() => {
        selectedAlbumId = null;
        isOpenAlbumDetail = false;
    }}
>
    {#if selectedAlbumId}
        <AlbumDetail id={String(selectedAlbumId)} />
    {/if}
</SubPage>

<style lang="scss">
    section {
        .artist-name {
            display: flex;
            flex-direction: column;
            align-items: center;
            font-size: 1.25rem;
            font-weight: bold;
            margin: 3rem 0;

            :global(img) {
                width: 150px;
                height: 150px;
                object-fit: cover;
                border-radius: 50%;
                margin-bottom: 1rem;
            }
        }

        .section-title {
            padding: 1rem;
            font-size: 1.25rem;
            font-weight: bold;
            border-bottom: 1px solid #222;
            display: flex;
            align-items: center;
            justify-content: space-between;
        }

        .albums {
            padding: 0 1rem 1rem 1rem;
            margin-bottom: 3rem;

            ul {
                display: grid;
                grid-gap: 1rem;
                grid-template-columns: repeat(auto-fill, minmax(160px, 1fr));
                padding: 0;
                list-style: none;

                @media (max-width: 600px) {
                    grid-template-columns: repeat(2, minmax(0, 1fr));
                }
            }
        }

        .musics {
            ul {
                margin: 0;
                padding: 0;
                list-style: none;
            }
        }

        .play-all {
            display: flex;
            align-items: center;
            justify-content: space-between;
            gap: 0.75rem;
        }
    }
</style>
