// server/src/client2/src/pages/MusicList.tsx
import { prompt } from '@baejino/ui'
import { useStore } from 'badland-react'
import { useSearchParams } from 'react-router-dom'

import { MusicItem, SecondaryButton, StickyHeader } from '~/components'
import { Play } from '~/icon'

import { musicStore } from '~/store/music'
import { queueStore } from '~/store/queue'

export default function Music() {
    const [{ musics }] = useStore(musicStore)

    const [searchParams, setSearchParams] = useSearchParams()

    const handleSearch = async () => {
        const q = await prompt('Search keyword', searchParams.get('q') || '')
        setSearchParams({ q })
    }

    const filteredMusics = musics
        ?.filter(music =>
            music.name.toLowerCase().includes(searchParams.get('q')?.toLowerCase() || '') ||
            music.artist.name.toLowerCase().includes(searchParams.get('q')?.toLowerCase() || '') ||
            music.album.name.toLowerCase().includes(searchParams.get('q')?.toLowerCase() || '')
        )

    return (
        <>
            <StickyHeader>
                <SecondaryButton style={{ width: '160px' }} onClick={handleSearch}>
                    {searchParams.get('q') || 'Search'}
                </SecondaryButton>
                <SecondaryButton>
                    <Play /> Play
                </SecondaryButton>
            </StickyHeader>
            {filteredMusics.map(music => (
                <MusicItem
                    key={music.id}
                    albumName={music.album.name}
                    albumCover={music.album.cover}
                    artistName={music.artist.name}
                    musicName={music.name}
                    musicCodec={music.codec}
                    isLiked={music.isLiked}
                    onClick={() => queueStore.add(music.id)}
                    onLongPress={() => { }}
                />
            ))}
        </>
    )
}

// server/src/client/src/pages/MusicList.svelte
<script lang="ts">
    import { onMount } from "svelte";

    import MusicListItem from "../components/MusicListItem.svelte";
    import Shuffle from "../icons/Shuffle.svelte";
    import Play from "../icons/Play.svelte";
    import Sort from "../icons/Sort.svelte";

    import { shuffle } from "../modules/shuffle";

    import { useGradualRender } from "../hooks/useGradualRender";

    import {
        resetQueue,
        insertToQueue,
        musics,
        musicActionPanel,
        musicSortPanel,
    } from "../store";

    let search = "";
    let innerMusics = useGradualRender($musics);

    $: visibleMusics = $innerMusics.filter(
        (music) =>
            search === "" ||
            music.name.toLowerCase().includes(search.toLowerCase()) ||
            music.artist.name.toLowerCase().includes(search.toLowerCase())
    );

    onMount(() => {
        musics.subscribe((musics) => {
            $innerMusics = musics;
        });
    });
</script>

<div class="controls">
    <div>
        <input
            class="gray-input"
            type="text"
            placeholder="Search"
            bind:value={search}
        />
    </div>
    <div class="buttons">
        <button
            class="gray-button"
            on:click={() => resetQueue("Play All Music", visibleMusics)}
        >
            <Play />
            Play
        </button>
        <button
            class="gray-button"
            on:click={() =>
                resetQueue("Shuffle All Music", shuffle(visibleMusics))}
        >
            <Shuffle />
            Shuffle
        </button>
        <button
            class="gray-button"
            on:click={() => ($musicSortPanel.isOpen = true)}
        >
            <Sort />
        </button>
    </div>
</div>
<ul aria-label="Music List">
    {#each visibleMusics as music}
        <li>
            <MusicListItem
                albumName={music.album.name}
                albumCover={music.album.cover}
                artistName={music.artist.name}
                musicName={music.name}
                musicCodec={music.codec}
                isLiked={music.isLiked}
                onClick={() => insertToQueue(music)}
                onLongPress={() => {
                    musicActionPanel.update(() => ({
                        isOpen: true,
                        music,
                    }));
                }}
            />
        </li>
    {/each}
</ul>

<style lang="scss">
    ul {
        margin: 0;
        padding: 0;
        width: 100%;
        list-style: none;
    }
</style>
