// server/src/client/src/pages/PlaylistDetail.svelte
<script lang="ts">
    import { onMount } from "svelte";

    import MusicListItem from "../components/MusicListItem.svelte";
    import Checkbox from "../components/Checkbox.svelte";

    import Play from "../icons/Play.svelte";
    import TrashBin from "../icons/TrashBin.svelte";
    import CheckBox from "../icons/CheckBox.svelte";

    import type { Playlist } from "../models/type";

    import { confirm } from "../modules/ui/modal";

    import { getPlaylist } from "../api";

    import {
        resetQueue,
        insertToQueue,
        musicActionPanel,
        musics,
    } from "../store";
    import * as socketManager from "../socket";

    export let id = "";

    let playlist: Playlist = null;
    let enableSelect = false;
    let selectedMusics: Playlist["musics"] = [];

    const handleChangeCheckbox = (music: Playlist["musics"][0]) => {
        if (selectedMusics.find((m) => m.id === music.id)) {
            selectedMusics = selectedMusics.filter((m) => m.id !== music.id);
        } else {
            selectedMusics = [...selectedMusics, music];
        }
    };

    const handleDeleteMusics = async () => {
        if (
            await confirm(
                `Delete ${selectedMusics.length} musics from ${playlist.name}?`
            )
        ) {
            socketManager.socket.emit(socketManager.PLAYLIST_REMOVE_MUSIC, {
                id: playlist.id,
                musicIds: selectedMusics.map((m) => m.id),
            });
            playlist.musics = playlist.musics.filter(
                (m) => !selectedMusics.find((sm) => sm.id === m.id)
            );
            selectedMusics = [];
        }
    };

    onMount(async () => {
        if (!id) {
            return;
        }

        const { data } = await getPlaylist(id);
        playlist = data.playlist;

        musics.subscribe((value) => {
            playlist.musics = playlist.musics.map((music) => {
                music.isLiked = value.find((m) => m.id === music.id)?.isLiked;
                return music;
            });
        });
    });
</script>

{#if playlist}
    <div class="playlist">
        <div class="playlist-title">
            {playlist.name}
        </div>
        <div class="play-all">
            <button
                on:click={() => {
                    resetQueue(playlist.name, playlist.musics);
                }}
            >
                <Play />
            </button>
        </div>
    </div>
{/if}

{#if playlist?.musics}
    <div class="playlist-items">
        <div class="actions">
            <button
                class="clickable"
                class:active={enableSelect}
                on:click={() => (enableSelect = !enableSelect)}
            >
                <CheckBox />
                Select
            </button>
        </div>
        <ul>
            {#each playlist.musics as music}
                <li>
                    {#if enableSelect}
                        <div class="checkbox">
                            <Checkbox
                                checked={selectedMusics.some(
                                    (m) => m.id === music.id
                                )}
                                onChange={() => handleChangeCheckbox(music)}
                            />
                        </div>
                    {/if}
                    <MusicListItem
                        albumCover={music.album.cover}
                        artistName={music.artist.name}
                        musicName={music.name}
                        musicCodec={music.codec}
                        isLiked={music.isLiked}
                        onClick={() => {
                            if (enableSelect) {
                                handleChangeCheckbox(music);
                                return;
                            }
                            insertToQueue(music);
                        }}
                        onLongPress={() => {
                            musicActionPanel.update(() => ({
                                isOpen: true,
                                music,
                            }));
                        }}
                    />
                </li>
            {/each}
        </ul>
        {#if enableSelect && selectedMusics.length > 0}
            <div class="select-actions">
                <button
                    class="clickable"
                    on:click={() => {
                        resetQueue(playlist.name, selectedMusics);
                    }}
                >
                    <Play />
                    Play
                </button>
                <button class="clickable" on:click={handleDeleteMusics}>
                    <TrashBin />
                    Delete
                </button>
            </div>
        {/if}
    </div>
{/if}

<style lang="scss">
    @import "../styles/var.scss";

    .playlist {
        position: relative;
        display: flex;
        flex-direction: column;
        align-items: center;
        gap: 1rem;
        padding: 2rem 1rem;
        background-color: #111;
        border-radius: 0.5rem;

        :global(.album-cover) {
            width: 100%;
            max-width: 300px;
            border-radius: 0.5rem;
        }

        .playlist-title {
            font-size: 1.25rem;
            font-weight: bold;
        }

        .play-all {
            position: absolute;
            bottom: 0;
            right: 0.5rem;
            display: flex;
            align-items: center;
            justify-content: center;
            transform: translateY(50%);

            button {
                border-radius: 100%;
                width: 4rem;
                height: 4rem;
                background-color: #1c1c1c;
                border: 4px solid #000;
                color: #ccc;
                transition: background-color 0.2s;

                :global(svg) {
                    width: 1.5rem;
                    height: 1.5rem;
                }

                @media (min-width: 1024px) {
                    &:hover {
                        background-color: #2a2a2a;
                    }
                }
            }
        }
    }

    .playlist-items {
        margin-top: 1.75rem;
        display: flex;
        flex-direction: column;
        gap: 1rem;
        flex: 1;

        .checkbox {
            margin-left: 1rem;
        }

        .actions {
            padding: 0 1rem;
        }

        button {
            display: flex;
            align-items: center;
            gap: 0.25rem;

            &.active {
                color: $PRIMARY_COLOR;
            }

            :global(svg) {
                width: 1.25rem;
                height: 1.25rem;
            }
        }

        ul {
            flex: 1;
            margin: 0;
            padding: 0;
            width: 100%;
            list-style: none;

            li {
                display: flex;
                align-items: center;
            }
        }

        .select-actions {
            position: sticky;
            bottom: 0;
            left: 0;
            display: flex;
            align-items: center;
            justify-content: space-between;
            margin-top: 1rem;
            padding: 0.5rem 0;
            background-color: $PRIMARY_COLOR;

            button {
                display: flex;
                align-items: center;
                flex-direction: column;
                justify-content: center;
                font-size: 0.75rem;
                font-weight: bold;
            }
        }
    }
</style>

// server/src/client/src/pages/PlaylistDetail.tsx
import { useEffect, useState } from 'react'
import styled from '@emotion/styled'
import { useQuery, useQueryClient } from 'react-query'
import { useStore } from 'badland-react'
import { useNavigate, useParams } from 'react-router-dom'
import { theme } from '@baejino/style'

import { CSS } from '@dnd-kit/utilities'
import { DragEndEvent } from '@dnd-kit/core'
import { arrayMove, useSortable } from '@dnd-kit/sortable'

import { GridImage, MusicActionPanelContent, MusicItem, MusicSelector, SecondaryButton, StickyHeader, VerticalSortable } from '~/components'
import { CheckBox, Menu, Play, TrashBin } from '~/icon'

import { panel } from '~/modules/panel'

import { Music } from '~/models/type'

import { getPlaylist } from '~/api'
import {
    PLAYLIST_CHANGE_MUSIC_ORDER,
    PLAYLIST_REMOVE_MUSIC,
    PlaylistListener,
    socket
} from '~/socket'

import { musicStore } from '~/store/music'
import { queueStore } from '~/store/queue'

const Item = styled.div`
    display: flex;
    flex-direction: row;
    align-items: center;

    .checkbox {
        margin-left: 1rem;

        svg {
            width: 1rem;
            height: 1rem;
        }

        &.active svg {
            color: #ccc;
            fill: ${theme.COLOR_PURPLE_PROMINENT};
        }
    }
`

const Container = styled.div`
    display: flex;
    flex-direction: column;
    flex: 1;

    .header {
        display: flex;
        align-items: center;
        justify-content: center;
        flex-direction: column;
        background-color: #111;
        padding: 3rem 1rem;

        .cover {
            width: 300px;
            height: 300px;
            margin-bottom: 1rem;
        }

        h1 {
            font-size: 1.25rem;
            font-weight: bold;
        }
    }

    .select-actions {
        position: sticky;
        bottom: 0;
        left: 0;
        display: flex;
        align-items: center;
        justify-content: space-between;
        padding: 0.5rem 0;
        background-color: ${theme.COLOR_PURPLE_PROMINENT};

        button {
            display: flex;
            align-items: center;
            flex-direction: column;
            justify-content: center;
            font-size: 0.75rem;
            font-weight: bold;
            gap: 0.25rem;

            svg {
                width: 1.25rem;
                height: 1.25rem;
            }
        }
    }
`


function PlaylistDndMusicItem({
    music,
    isSelectMode,
    isSelected,
    onClick,
    onSelect,
    onLongPress,
}: {
    music: Music
    isSelectMode: boolean
    isSelected: boolean
    onClick: () => void
    onSelect: () => void
    onLongPress: () => void
}) {
    const { attributes, listeners, setNodeRef, transform, transition } = useSortable({ id: music.id })
    const style = {
        transform: CSS.Transform.toString(transform),
        transition,
    }

    return (
        <Item ref={setNodeRef} style={style} {...attributes}>
            {isSelectMode ? (
                <button
                    className={`icon-button checkbox ${isSelected ? 'active' : ''} `}
                    onClick={onSelect}
                >
                    <CheckBox />
                </button>
            ) : (
                <div className="icon-button checkbox" {...listeners} style={{ cursor: 'grab', touchAction: 'none' }}>
                    <Menu />
                </div>
            )}
            <div style={{ flex: 1, maxWidth: 'calc(100% - 4rem)' }}>
                <MusicItem
                    albumName={music.album.name}
                    albumCover={music.album.cover}
                    artistName={music.artist.name}
                    musicName={music.name}
                    musicCodec={music.codec}
                    isLiked={music.isLiked}
                    onClick={isSelectMode ? onSelect : onClick}
                    onLongPress={onLongPress}
                />
            </div>
        </Item>
    )
}

export default function PlaylistDetail() {
    const navigate = useNavigate()

    const { id } = useParams<{ id: string }>()

    const queryClient = useQueryClient()

    const { data: playlist } = useQuery(['playlist', id], () => getPlaylist(id!).then(res => res.data.playlist), {
        enabled: !!id,
    })

    const [{ musicMap }] = useStore(musicStore)

    const [isSelectMode, setIsSelectMode] = useState(false)
    const [selectedItems, setSelectedItems] = useState<string[]>([])

    const handleDragEnd = (event: DragEndEvent) => {
        const { active, over } = event

        if (playlist && over && active.id !== over.id) {
            const oldIndex = playlist.musics.findIndex(({ id }) => id === active.id)
            const newIndex = playlist.musics.findIndex(({ id }) => id === over.id)
            const newMusics = arrayMove(playlist.musics, oldIndex, newIndex)
            PlaylistListener.changeMusicOrder(playlist.id, newMusics.map(({ id }) => id))

            queryClient.setQueryData(['playlist', id], () => {
                return {
                    ...playlist,
                    musics: newMusics,
                }
            })
        }
    }

    useEffect(() => {
        const changeMusicOrderHandler = () => {
            queryClient.invalidateQueries(['playlist', id])
        }
        const removeMusicHandler = () => {
            queryClient.invalidateQueries(['playlist', id])
        }
        socket.on(PLAYLIST_CHANGE_MUSIC_ORDER, changeMusicOrderHandler)
        socket.on(PLAYLIST_REMOVE_MUSIC, removeMusicHandler)
        return () => {
            socket.off(PLAYLIST_CHANGE_MUSIC_ORDER, changeMusicOrderHandler)
            socket.off(PLAYLIST_REMOVE_MUSIC, removeMusicHandler)
        }
    }, [id, queryClient])

    useEffect(() => {
        setSelectedItems([])
    }, [isSelectMode])

    if (!playlist) {
        return null
    }

    return (
        <Container>
            <div className="header">
                <GridImage
                    className="cover"
                    images={playlist.musics.slice(0, 16).map((music) => musicMap.get(music.id)?.album.cover ?? '')}
                />
                <h1>{playlist.name}</h1>
            </div>
            <StickyHeader>
                <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
                    <MusicSelector
                        active={isSelectMode}
                        label={isSelectMode ? `${selectedItems.length} selected` : `${playlist.musics.length} musics`}
                        onClick={() => setIsSelectMode(!isSelectMode)}
                        onSelectAll={() => setSelectedItems(playlist.musics.map(({ id }) => id))}
                    />
                </div>
                <SecondaryButton onClick={() => queueStore.reset(playlist.musics.map(({ id }) => id))}>
                    <Play /> Play
                </SecondaryButton>
            </StickyHeader >
            <div style={{ flex: 1 }}>
                <VerticalSortable items={playlist.musics.map(({ id }) => id)} onDragEnd={handleDragEnd}>
                    {playlist.musics.map(({ id }) => {
                        const music = musicMap.get(id)

                        if (!music) return null

                        return (
                            <PlaylistDndMusicItem
                                key={music.id}
                                music={music}
                                isSelectMode={isSelectMode}
                                isSelected={selectedItems.includes(music.id)}
                                onClick={() => queueStore.add(music.id)}
                                onSelect={() => {
                                    if (selectedItems.includes(music.id)) {
                                        setSelectedItems(selectedItems.filter(item => item !== music.id))
                                    } else {
                                        setSelectedItems([...selectedItems, music.id])
                                    }
                                }}
                                onLongPress={() => panel.open({
                                    content: (
                                        <MusicActionPanelContent
                                            id={music.id}
                                            onAlbumClick={() => navigate(`/album/${music.album.id}`)}
                                            onArtistClick={() => navigate(`/artist/${music.artist.id}`)}
                                        />
                                    )
                                })}
                            />
                        )
                    })}
                </VerticalSortable>
            </div>
            {isSelectMode && selectedItems.length > 0 && (
                <div className="select-actions">
                    <button className="clickable" onClick={async () => {
                        PlaylistListener.removeMusic(playlist.id, selectedItems)
                        setIsSelectMode(false)
                    }}>
                        <TrashBin />
                        <span>Delete</span>
                    </button>
                </div>
            )}
        </Container>
    )
}
