// server/src/client/src/pages/Setting.tsx
import { confirm, toast } from '@baejino/ui'
import styled from '@emotion/styled'
import { useStore } from 'badland-react'
import { useEffect, useState } from 'react'

import { SecondaryButton, Select } from '~/components'

import { ConnectorListener, socket } from '~/socket'

import { connectorStore } from '~/store/connector'
import { queueStore } from '~/store/queue'

const Container = styled.div`
    padding: 1rem;

    section {
        display: flex;
        flex-direction: column;
        border-bottom: 1px solid #222;
        padding: 2.5rem 0;
        gap: 1rem;

        h3 {
            font-size: 1rem;
            font-weight: 600;
            color: #656565;
        }

        p {
            font-size: 0.8rem;
            font-weight: 400;
            color: #d0d0d0;
        }

        .progress-text {
            font-size: 0.8rem;
            font-weight: 400;
            color: #ffffff;
        }
    }

    .connector {
        display: flex;
        align-items: center;
        flex-wrap: wrap;
        font-size: 0.825rem;
        gap: 0.5rem;

        .date {
            font-size: 0.825rem;
            color: #999;
        }

        .this-device, .kick {
            padding: 0.125rem 0.5rem;
            border-radius: 0.5rem;
            background-color: #3d3493;
            font-size: 0.75rem;
            color: #eee;
        }

        .kick {
            cursor: pointer;
            background-color: #333;
        }
    }
`

const PLAY_MODES = [{
    value: 'immediately',
    label: 'Play immediately'
}, {
    value: 'later',
    label: 'Play later'
}]

const INSERT_MODES = [{
    value: 'first',
    label: 'Add to the top of the queue'
}, {
    value: 'last',
    label: 'Add to the bottom of the queue'
}, {
    value: 'after',
    label: 'Add to the next of the current music'
}]

export default function Setting() {
    const [{ connectors }] = useStore(connectorStore)
    const [{ playMode, insertMode }] = useStore(queueStore)
    const [progressMessage, setProgressMessage] = useState('')

    const handleClickSyncMusic = async (force: boolean) => {
        if (
            force &&
            !(await confirm(
                'Please only proceed with the update if it is recommended by the developer. Are you sure you want to proceed?'
            ))
        ) {
            return
        }
        socket.emit('sync-music', { force })
    }

    useEffect(() => {
        socket.on('sync-music', (serverMessage: string | 'done' | 'error') => {
            if (serverMessage === 'done' || serverMessage === 'error') {
                if (serverMessage === 'done') {
                    toast('Completed sync music')
                } else if (serverMessage === 'error') {
                    toast('Error while sync music')
                }

                setTimeout(() => {
                    setProgressMessage('')
                }, 1000)
            }
            setProgressMessage(serverMessage)
        })

        return () => {
            socket.off('sync-music')
        }
    }, [])

    return (
        <Container>
            <section>
                <h3>Synchronization</h3>
                <p>Sync from your server</p>
                {progressMessage && (
                    <p className="progress-text">{progressMessage}</p>
                )}
                <div style={{ display: 'flex', gap: '1rem' }}>
                    <SecondaryButton onClick={() => handleClickSyncMusic(false)}>
                        Sync
                    </SecondaryButton>
                    <SecondaryButton onClick={() => handleClickSyncMusic(true)}>
                        Force Sync
                    </SecondaryButton>
                </div>
            </section>
            <section>
                <h3>Play Mode</h3>
                <p>When you add a music to the queue, It will...</p>
                <Select
                    selected={PLAY_MODES.find(({ value }) => value === playMode)}
                    options={PLAY_MODES}
                    onChange={(value) => queueStore.setPlayMode(value as typeof playMode)}
                />
                <Select
                    selected={INSERT_MODES.find(({ value }) => value === insertMode)}
                    options={INSERT_MODES}
                    onChange={(value) => queueStore.setInsertMode(value as typeof insertMode)}
                />
            </section>
            <section>
                <h3>Connectors</h3>
                {connectors.map((connector) => (
                    <div key={connector.id} className="connector">
                        <span>{connector.userAgent}</span>
                        <span className="date">{new Date(connector.connectedAt).toLocaleDateString()}</span>
                        {connector.id === socket.id ? (
                            <span className="this-device">This device</span>
                        ) : (
                            <button
                                className="kick"
                                onClick={() => ConnectorListener.remove(connector.id)}>
                                Remove
                            </button>
                        )}
                    </div>
                ))}
            </section>
            <section>
                <h3>Have a problem?</h3>
                <div style={{ display: 'flex', gap: '1rem' }}>
                    <SecondaryButton onClick={() => window.location.reload()}>
                        Try Refresh
                    </SecondaryButton>
                </div>
            </section>
        </Container >
    )
}

// server/src/client/src/pages/Setting.svelte
<script lang="ts">
    import { onDestroy, onMount } from "svelte";
    import { confirm, toast } from "@baejino/ui";

    import { Select } from "~/components";

    import { socket } from "~/socket";

    import { queue } from "~/store";
    import type { QueueInsertMode, QueuePlayMode } from "~/store";

    let isLoading = false;
    let message = "";
    let connectors: {
        id: string;
        userAgent: string;
        connectedAt: number;
    }[] = [];

    onMount(() => {
        socket.on("sync-music", (serverMessage: string | "done" | "error") => {
            if (serverMessage === "done" || serverMessage === "error") {
                isLoading = false;
                if (serverMessage === "done") {
                    toast("Completed syncing music");
                } else if (serverMessage === "error") {
                    toast("Error while syncing music");
                }
            }
            message = serverMessage;
        });

        socket.emit("get-connectors");

        socket.on("get-connectors", (connectorsData) => {
            connectors = connectorsData;
        });
    });

    onDestroy(() => {
        socket.off("sync-music");
        socket.off("get-connectors");
    });

    const handleClickSyncMusic = async (force: boolean) => {
        if (
            force &&
            !(await confirm(
                "Please only proceed with the update if it is recommended by the developer. Are you sure you want to proceed?"
            ))
        ) {
            return;
        }
        isLoading = true;
        socket.emit("sync-music", { force });
    };

    const handleClickRefreshApp = () => {
        location.reload();
    };

    const handleChangePlayMode = (value: QueuePlayMode) => {
        queue.update((state) => ({
            ...state,
            playMode: value,
        }));
    };

    const handleChangeQueueMode = (value: QueueInsertMode) => {
        queue.update((state) => ({
            ...state,
            insertMode: value,
        }));
    };
</script>

<div class="continer">
    <h3>Synchronization</h3>
    <section>
        <p>Synchronize the music with your server</p>
        {#if isLoading}
            <p class="message">{message}</p>
        {/if}
        <div class="buttons">
            {#if isLoading}
                <button disabled={isLoading}>Syncing...</button>
            {:else}
                <button on:click={() => handleClickSyncMusic(false)}>
                    Start
                </button>
                <button on:click={() => handleClickSyncMusic(true)}>
                    Force Start
                </button>
            {/if}
        </div>
    </section>
    <h3>Play Mode</h3>
    <section>
        When you add music to the queue, it will...
        <div class="buttons">
            <Select
                title="It will..."
                value={$queue.playMode}
                onChange={handleChangePlayMode}
                options={[
                    { value: "later", label: "Play later" },
                    { value: "immediate", label: "Play immediately" },
                ]}
            />
            <Select
                title="It will..."
                value={$queue.insertMode}
                onChange={handleChangeQueueMode}
                options={[
                    {
                        value: "after",
                        label: "Be added after the current music",
                    },
                    {
                        value: "before",
                        label: "Be added before the current music",
                    },
                    {
                        value: "last",
                        label: "Be added at the end of the queue",
                    },
                ]}
            />
        </div>
    </section>
    <h3>Connectors</h3>
    <section style="align-items: flex-start;">
        {#each connectors as connector, idx}
            <div
                style="
                    display: flex;
                    justify-content: space-between;
                    align-items: center;
                    flex-wrap: wrap;
                    font-size: 0.825rem;
                    gap: 0.5rem;
                "
            >
                {idx + 1}. {connector.userAgent}
                <span
                    style="
                        font-size: 0.825rem;
                        color: #999;
                    "
                >
                    {new Date(connector.connectedAt).toLocaleString()}
                </span>
                {#if connector.id === socket.id}
                    <span
                        style="
                            padding: 0.25rem 0.5rem;
                            border-radius: 0.5rem;
                            background-color: #333;
                            font-size: 0.75rem;
                            color: #eee;
                        "
                    >
                        This device
                    </span>
                {:else}
                    <button
                        style="padding: 0.25rem 0.5rem;"
                        on:click={() =>
                            socket.emit("disconnect-connector", {
                                id: connector.id,
                            })}
                    >
                        Disconnect
                    </button>
                {/if}
            </div>
        {/each}
    </section>
    <h3>Have a problem?</h3>
    <section style="justify-content: space-between;">
        <div>
            <button on:click={handleClickRefreshApp}>Try Refresh</button>
        </div>
    </section>
</div>

<style lang="scss">
    .continer {
        padding: 1rem;
    }

    h3 {
        font-size: 1rem;
        font-weight: 600;
        color: #656565;
        margin: 2rem 0 0;
    }

    .message {
        font-size: 0.825rem;
        color: #999;
    }

    .buttons {
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        gap: 0.5rem;
    }

    button {
        padding: 0.5rem 1rem;
        border-radius: 0.5rem;
        font-size: 0.825rem;
        border: 1px solid #333;
        background-color: #000;
        color: #eee;

        &:disabled {
            opacity: 0.5;
        }
    }

    section {
        display: flex;
        flex-direction: column;
        gap: 0.5rem;
        border-bottom: 1px solid #222;
        padding: 1rem 0 2rem;
    }
</style>
