// server/src/client/src/components/atom/Select.svelte
<script lang="ts">
    import { Menu } from "~/icons";

    export let options: {
        value: string;
        label: string;
    }[] = [];
    export let title: string = null;
    export let value: string;
    export let onChange: (value: string) => void;

    let isOpen = false;

    const handleClickOption = (value: string) => {
        onChange(value);
        isOpen = false;
    };

    $: label =
        options.find((option) => option.value === value)?.label || "Select";
</script>

<div class="select">
    <button class="opnner" on:click={() => (isOpen = !isOpen)}>
        <Menu />
        {label}
    </button>
    <button
        class="backdrop clickable"
        class:open={isOpen}
        on:click={() => (isOpen = false)}
    >
        {#if title}
            <div class="title" class:open={isOpen}>
                {title}
            </div>
        {/if}
        <ul class="menus" class:open={isOpen}>
            {#each options as option}
                <li>
                    <button
                        class:active={option.value === value}
                        on:click={() => handleClickOption(option.value)}
                    >
                        {#if option.value === value}
                            <span class="checkmark">✓</span>
                        {/if}
                        {option.label}
                    </button>
                </li>
            {/each}
        </ul>
    </button>
</div>

<style lang="scss">
    .opnner {
        padding: 0.5rem 1rem;
        border-radius: 0.5rem;
        border: 1px solid #333;
        background-color: #000;
        font-size: 0.825rem;
        color: #eee;
        display: flex;
        align-items: center;
        gap: 0.25rem;

        :global(svg) {
            width: 1rem;
            height: 1rem;
            margin-right: 0.5rem;
        }
    }

    .backdrop {
        position: fixed;
        display: flex;
        align-items: center;
        flex-direction: column;
        justify-content: center;
        gap: 1rem;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        padding: 1rem;
        opacity: 0;
        z-index: 1;
        pointer-events: none;
        background-color: rgba(0, 0, 0, 0.88);
        transition: opacity 0.2s ease-in-out;

        &.open {
            opacity: 1;
            pointer-events: all;
        }
    }

    .title {
        font-size: 0.875rem;
        color: #888;
        transform: translateY(-1rem);
        transition: all 0.2s ease-in-out;

        &.open {
            transform: translateY(0);
            opacity: 1;
        }
    }

    .menus {
        list-style: none;
        display: flex;
        flex-direction: column;
        width: 500px;
        max-width: 100%;
        padding: 0;
        margin: 0.5rem 0 0;
        background-color: #000;
        border: 1px solid #333;
        border-radius: 0.5rem;
        opacity: 0;
        transform: translateY(1rem);
        pointer-events: none;
        transition: all 0.2s ease-in-out;

        &.open {
            opacity: 1;
            transform: translateY(0);
            pointer-events: all;
        }

        li {
            padding: 0;
            margin: 0;

            &:not(:last-child) {
                border-bottom: 1px solid #333;
            }

            button {
                background-color: inherit;
                border: none;
                width: 100%;
                outline: none;
                color: #eee;
                padding: 1rem;
                display: flex;
                align-items: center;
                justify-content: flex-start;
                font-size: 1rem;

                .checkmark {
                    margin-right: 0.5rem;
                    color: #abf176;
                }

                &.active {
                    background-color: #222;
                }

                &:hover {
                    background-color: #222;
                }
            }
        }
    }
</style>

// server/src/client/src/components/shared/Select.tsx
import styled from '@emotion/styled';
import { useEffect, useRef, useState } from 'react';
import { Menu } from '~/icon';

interface Option {
    value: string;
    label: string;
}

interface SelectProps {
    selected?: Option;
    options: Option[];
    onChange: (value: string) => void;
}

const Styles = styled.div`
    @keyframes slide-down {
        0% {
            opacity: 0;
            transform: translateY(-0.5rem);
        }
        100% {
            opacity: 1;
            transform: translateY(0);
        }
    }

    position: relative;
    display: inline-block;
    font-size: 0.825rem;

    .selected {
        display: flex;
        align-items: center;
        gap: 1rem;
        padding: 0.8rem 1rem;
        border: 1px solid #333;
        border-radius: 8px;
        cursor: pointer;

        svg {
            width: 1rem;
            height: 1rem;
            fill: #fff;
        }
    }

    .options {
        position: absolute;
        top: 100%;
        left: 0;
        right: 0;
        background-color: #000;
        border: 1px solid #333;
        border-radius: 8px;
        border-top: none;
        border-top-left-radius: 0;
        border-top-right-radius: 0;
        display: none;
        z-index: 1;

        div {
            padding: 0.825rem 1rem;
            cursor: pointer;

            &:hover {
                background-color: #333;
            }
        }
    }

    &.open {
        .selected {
            border-bottom-left-radius: 0;
            border-bottom-right-radius: 0;
        }

        .options {
            display: block;
            animation: slide-down 0.1s ease;
        }
    }
`;

export default function Select({ selected, options, onChange }: SelectProps) {
    const ref = useRef<HTMLDivElement>(null);
    const [isOpen, setIsOpen] = useState(false);

    useEffect(() => {
        function handleClickOutside(event: MouseEvent) {
            if (ref.current && !ref.current.contains(event.target as Node)) {
                setIsOpen(false);
            }
        }

        document.addEventListener('mousedown', handleClickOutside);

        return () => {
            document.removeEventListener('mousedown', handleClickOutside);
        };
    }, [ref]);

    return (
        <Styles ref={ref} className={`${isOpen ? 'open' : ''}`}>
            <div className="selected" onClick={() => setIsOpen(!isOpen)}>
                <Menu />
                {selected ? (
                    <div>{selected.label}</div>
                ) : (
                    <div>Select an option</div>
                )}
            </div>
            <div className="options">
                {options.map((option) => (
                    <div
                        key={option.value}
                        onClick={() => {
                            onChange(option.value);
                            setIsOpen(false);
                        }}>
                        {option.label}
                    </div>
                ))}
            </div>
        </Styles>
    );
}
