// server/src/client/src/components/MusicListItem.svelte
<script lang="ts">
    import Image from "./Image.svelte";
    import Heart from "../icons/Heart.svelte";
    import MoreVerticalFill from "../icons/MoreVerticalFill.svelte";

    export let albumName: string = null;
    export let albumCover: string = null;
    export let artistName: string;
    export let trackNumber: number = null;
    export let musicName: string;
    export let musicCodec: string = null;
    export let isLiked: boolean = false;
    export let onClick: () => void;
    export let onLongPress: () => void = null;
</script>

<button
    class="clickable item"
    on:click={onClick}
    on:contextmenu={(e) => {
        e.preventDefault();
        onLongPress?.();
    }}
>
    {#if albumCover !== null}
        <Image class="album-art" alt={albumName} src={albumCover} />
    {/if}
    <div class="row">
        <div class="info">
            <div class="title">
                {#if trackNumber !== null}
                    <span class="track-number">
                        {trackNumber}.
                    </span>
                {/if}
                {musicName}
                {#if musicCodec && musicCodec.toLowerCase() === "flac"}
                    <span class="codec">
                        {musicCodec}
                    </span>
                {/if}
            </div>
            <div class="artist">
                <div>
                    {artistName}
                </div>
            </div>
        </div>
        {#if onLongPress}
            <button
                class="icon-button"
                class:liked={isLiked}
                on:click={(e) => {
                    e.stopPropagation();
                    onLongPress();
                }}
            >
                {#if isLiked}
                    <Heart />
                {:else}
                    <MoreVerticalFill />
                {/if}
            </button>
        {/if}
    </div>
</button>

<style lang="scss">
    .row {
        display: flex;
        flex-direction: row;
        align-items: center;
        justify-content: space-between;
        width: 100%;
        gap: 0.5rem;

        .icon-button {
            color: #eee;
            width: 2.5rem;
            height: 2.5rem;

            :global(svg) {
                width: 1.125rem;
                height: 1.125rem;
            }

            &.liked {
                :global(svg) {
                    fill: #a076f1;
                    color: #a076f1;
                }
            }

            @media (min-width: 1024px) {
                &:hover {
                    background-color: rgba(255, 255, 255, 0.1);
                }
            }
        }
    }

    .item {
        color: #eee;
        font-size: 0.8rem;
        cursor: pointer;
        padding: 1rem;
        display: flex;
        flex-direction: row;
        align-items: center;
        gap: 0.5rem;
        width: 100%;

        @media (min-width: 1024px) {
            &:hover {
                background-color: rgba(255, 255, 255, 0.1);
            }
        }

        .artist {
            display: flex;
            align-items: center;
            justify-content: space-between;
            flex-wrap: wrap;
        }

        .title {
            .track-number {
                margin-right: 0.25rem;
                color: #666;
                font-size: 0.8rem;
                font-weight: 400;
            }

            .codec {
                border: 1px solid #333;
                color: #eee;
                margin-left: 0.25rem;
                padding: 0.1rem 0.5rem;
                border-radius: 0.5rem;
                font-size: 0.6rem;
                font-weight: 400;
            }
        }
    }
</style>

// packages/client/src/components/music/MusicListItem/MusicListItem.tsx
import classNames from 'classnames';
const cx = classNames;

import { IconButton, TrackArtwork } from '~/components/shared';
import { Heart, VerticalDots } from '~/icon';

interface MusicListItemProps {
    id?: number;
    albumName: string;
    albumCover?: string;
    artistName: string;
    trackNumber?: number;
    musicName: string;
    musicCodec?: string;
    isLiked?: boolean;
    isHated?: boolean;
    hideAlbumArt?: boolean;
    onClick?: () => void;
    onLongPress?: () => void;
}

const MusicListItem = ({
    albumName,
    albumCover,
    artistName,
    trackNumber,
    musicName,
    musicCodec,
    isLiked,
    isHated,
    hideAlbumArt,
    onClick,
    onLongPress
}: MusicListItemProps) => {
    return (
        <button
            type="button"
            className={cx(
                'group/row flex w-full cursor-pointer flex-row items-center gap-4 px-6 py-4 text-left text-[var(--b-color-text)] transition-colors',
                'hover:bg-[image:var(--b-gradient-row-hover)] active:bg-[var(--b-color-active)]',
                { 'opacity-40': isHated }
            )}
            onClick={onClick}
            onContextMenu={(e) => {
                e.preventDefault();
                onLongPress?.();
            }}>
            {hideAlbumArt ? (
                <span className="w-12 shrink-0 text-center text-sm text-[var(--b-color-text-muted)]">
                    {trackNumber ?? '·'}
                </span>
            ) : (
                <TrackArtwork src={albumCover} alt={albumName} />
            )}
            <span className="flex min-w-0 flex-1 flex-row items-center justify-between gap-2">
                <span className={cx('flex min-w-0 flex-1 flex-col gap-1', { 'max-w-[calc(100%-40px-var(--b-spacing-md))]': typeof onLongPress === 'function' })}>
                    <span className="flex min-w-0 items-center gap-1 overflow-hidden text-ellipsis whitespace-nowrap text-sm font-medium text-[var(--b-color-text)]">
                        {!!trackNumber && !hideAlbumArt && (
                            <span className="min-w-6 text-[var(--b-color-text-muted)]">{trackNumber}.</span>
                        )}
                        <span className="truncate">{musicName}</span>
                        {musicCodec && musicCodec.toLowerCase() === 'flac' && (
                            <span className="shrink-0 text-[0.625rem] font-semibold uppercase tracking-[0.04em] text-[var(--b-color-point)]">{musicCodec}</span>
                        )}
                    </span>
                    <span className="truncate text-sm text-[var(--b-color-text-tertiary)]">
                        {artistName}
                    </span>
                </span>
                {onLongPress && (
                    <IconButton
                        aria-label={`Open actions for ${musicName}`}
                        active={isLiked}
                        className="h-10 w-10"
                        onClick={(e) => {
                            e.stopPropagation();
                            onLongPress?.();
                        }}>
                        {isLiked ? <Heart /> : <VerticalDots />}
                    </IconButton>
                )}
            </span>
        </button>
    );
};

export default MusicListItem;
