// server/src/client/src/components/BottomPanel.tsx
import styled from '@emotion/styled'

interface BottomPanelProps {
    title?: string
    isOpen: boolean
    onClose?: () => void
    children: React.ReactNode
}

const Container = styled.div`
    @keyframes fade-in {
        from {
            opacity: 0;
        }
        to {
            opacity: 1;
        }
    }

    @keyframes slide-in {
        from {
            transform: translateY(100%);
        }
        to {
            transform: translateY(0);
        }
    }

    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    display: none;
    flex-direction: column;
    z-index: 110;
    pointer-events: none;
    background-color: rgba(0, 0, 0, 0.88);

    &.open {
        pointer-events: all;
        display: flex;
        animation: fade-in 0.2s ease-in-out;
    }

    .backdrop {
        cursor: pointer;
        width: 100%;
        flex: 1;
    }

    .bottom-panel {
        width: 100%;
        height: fit-content;
        max-height: 80%;
        overflow-y: auto;
        padding: 32px 16px 16px;
        border-radius: 16px 16px 0 0;
        background-color: #151515;
        z-index: 100;

        &.open {
            animation: slide-in 0.2s ease-in-out;
        }
    }

    .panel-title {
        font-size: 0.875rem;
        color: #888;
    }
`

export default function PanelProvider({ title, isOpen, onClose, children }: BottomPanelProps) {
    return (
        <Container className={isOpen ? 'open' : ''}>
            <button className="clickable backdrop" onClick={onClose} />
            <div className={`bottom-panel ${isOpen ? 'open' : ''}`}>
                {title && <div className="panel-title">{title}</div>}
                {children}
            </div>
        </Container>
    )
}

// server/src/client/src/components/BottomPanel.svelte
<script lang="ts">
    export let isOpen = false;
    export let onClose: () => void = null;
</script>

<div class="wrapper" class:open={isOpen}>
    <button
        class="clickable backdrop"
        class:open={isOpen}
        on:click={() => {
            isOpen = false;
            onClose?.();
        }}
    />
    <div class="bottom-panel" class:open={isOpen}>
        <slot />
    </div>
</div>

<style lang="scss">
    .wrapper {
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        display: flex;
        flex-direction: column;
        z-index: 110;
        opacity: 0;
        pointer-events: none;
        background-color: rgba(0, 0, 0, 0.88);
        transition: opacity 0.2s ease-in-out;

        &.open {
            pointer-events: all;
            opacity: 1;
        }
    }

    .backdrop {
        width: 100%;
        flex: 1;
    }

    .bottom-panel {
        width: 100%;
        height: fit-content;
        max-height: 80%;
        overflow-y: auto;
        padding: 32px 16px 16px;
        border-radius: 16px 16px 0 0;
        background-color: #151515;
        z-index: 100;
        transform: translateY(100%);
        transition: transform 0.2s ease-in-out;

        &.open {
            transform: translateY(0);
        }
    }
</style>
