// server/src/client2/src/components/Image.tsx
import { useEffect, useRef } from "react";

interface ImageProps {
    src: string;
    alt?: string;
    loading?: "lazy" | "eager";
    className?: string;
}

export default function Image({
    src,
    alt,
    loading = "lazy",
    className,
}: ImageProps) {
    const ref = useRef<HTMLImageElement>(null);

    useEffect(() => {
        if (!ref.current || loading !== "lazy" || !src) {
            return;
        }

        const observer = new IntersectionObserver(([entry]) => {
            if (entry.isIntersecting) {
                const img = entry.target as HTMLImageElement;
                img.src = img.dataset.src as string;
                observer.unobserve(img);
            }
        });

        observer.observe(ref.current);

        return () => {
            observer.disconnect();
        }
    }, [loading, src]);

    return (
        <>
            {loading !== "lazy" ? (
                <img src={src} alt={alt} className={className} />
            ) : (
                <img
                    ref={ref}
                    src={"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIW2O4evXqfwAIgQN/QHwrfwAAAABJRU5ErkJggg=="}
                    alt={alt}
                    data-src={src}
                    className={className}
                />
            )}
        </>
    );
}

// server/src/client/src/components/Image.svelte
<script lang="ts">
    import { onMount } from "svelte";

    import { getImage } from "../modules/image";

    let imageRef: HTMLImageElement;
    export let src: string;
    export let alt: string;
    export let style: string = "";
    let className: string = "";
    export { className as class };
    export let loading: "lazy" | "eager" = "lazy";

    onMount(() => {
        if (loading === "lazy") {
            const observer = new IntersectionObserver((entries) => {
                entries.forEach((entry) => {
                    if (entry.isIntersecting) {
                        imageRef.src = getImage(src);
                        observer.unobserve(imageRef);
                    }
                });
            });
            observer.observe(imageRef);
        }
    });
</script>

{#if loading === "lazy"}
    <img
        bind:this={imageRef}
        class={className}
        src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIW2NgYGD4DwABBAEAwS2OUAAAAABJRU5ErkJggg=="
        {style}
    />
{:else}
    <img src={getImage(src)} {alt} class={className} {style} />
{/if}
