// server/src/client/src/components/atom/Image.svelte
<script lang="ts">
    import { afterUpdate, onDestroy, onMount } from "svelte";

    import { getImage } from "../../modules/image";

    let imageRef: HTMLImageElement;
    export let src: string;
    export let alt: string;
    export let style: string = "";
    let className: string = "";
    export { className as class };
    export let loading: "lazy" | "eager" = "lazy";

    let loadded: boolean = false;
    let observer: IntersectionObserver = null;

    const lazyLoading = () => {
        if (loading === "lazy") {
            observer = new IntersectionObserver((entries) => {
                entries.forEach((entry) => {
                    if (entry.isIntersecting) {
                        imageRef.src = getImage(src);
                        imageRef.onload = () => {
                            loadded = true;
                        };
                        observer.unobserve(imageRef);
                    }
                });
            });
            observer.observe(imageRef);
        }
    };

    onMount(() => {
        lazyLoading();
    });

    afterUpdate(() => {
        const prevSrc = imageRef.src.replace(location.origin, "");
        if (loading === "lazy" && loadded && prevSrc !== getImage(src)) {
            loadded = false;
            lazyLoading();
        }
    });

    onDestroy(() => {
        if (observer) {
            observer.unobserve(imageRef);
        }
    });
</script>

{#if loading === "lazy"}
    <img
        bind:this={imageRef}
        class={className}
        src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIW2NQV1f/DwACYwF11mMyYQAAAABJRU5ErkJggg=="
        {alt}
        {style}
    />
{:else}
    <img src={getImage(src)} {alt} class={className} {style} />
{/if}

// server/src/client/src/components/Image.tsx
import { useEffect, useRef } from 'react'
import { getImage } from '~/modules/image'

interface ImageProps {
    src?: string;
    alt?: string;
    loading?: 'lazy' | 'eager';
    className?: string;
}

export default function Image({
    src,
    alt,
    loading = 'lazy',
    className,
}: ImageProps) {
    const ref = useRef<HTMLImageElement>(null)

    useEffect(() => {
        if (!ref.current || loading !== 'lazy') {
            return
        }

        const observer = new IntersectionObserver(([entry]) => {
            if (entry.isIntersecting) {
                const img = entry.target as HTMLImageElement
                img.src = getImage(src)
                observer.unobserve(img)
            }
        })

        observer.observe(ref.current)

        return () => {
            observer.disconnect()
        }
    }, [loading, src])

    return (
        <>
            {loading !== 'lazy' ? (
                <img src={getImage(src)} alt={alt} className={className} />
            ) : (
                <img
                    ref={ref}
                    src={'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIW2NQV1f/DwACYwF11mMyYQAAAABJRU5ErkJggg=='}
                    alt={alt}
                    className={className}
                />
            )}
        </>
    )
}
