// server/src/client/src/components/Loading.tsx
import { theme } from '@baejino/style'
import styled from '@emotion/styled'

const Container = styled.div`
    flex: 1;
    display: flex;
    justify-content: center;
    align-items: center;

    @keyframes spin {
        0% {
            transform: rotate(0deg);
        }
        100% {
            transform: rotate(360deg);
        }
    }

    .spinner {
        animation: spin 0.75s infinite ease;
        border: 3px solid transparent;
        border-color: ${theme.COLOR_PURPLE_PROMINENT} transparent;
        width: 25px;
        height: 25px;
        border-radius: 50%;
    }
`

const Loading = () => (
    <Container>
        <div className="spinner" />
    </Container>
)

export default Loading

// server/src/client/src/components/Loading.svelte
<script lang="ts">
    import Beato from "./Beato.svelte";

    export let isLoading = false;
    export let message = "";
</script>

{#if isLoading}
    <div class="loading">
        <Beato spin />
        <div>{message}</div>
    </div>
{/if}

<style>
    .loading {
        width: 100%;
        height: 100%;
        background-color: rgba(0, 0, 0, 0.5);
        z-index: 9999;
        backdrop-filter: blur(20px);
        position: fixed;
        top: 0;
        left: 0;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        gap: 3rem;
    }
</style>
