// server/src/client/src/components/music/MusicListItem/MusicListItem.tsx
import styles from './MusicListItem.module.scss';
import classNames from 'classnames/bind';
const cx = classNames.bind(styles);

import { Image } from '~/components/shared';
import { Heart, VerticalDots } from '~/icon';

interface MusicListItemProps {
    id?: number;
    albumName: string;
    albumCover?: string;
    artistName: string;
    trackNumber?: number;
    musicName: string;
    musicCodec?: string;
    isLiked?: boolean;
    isHated?: boolean;
    onClick?: () => void;
    onLongPress?: () => void;
}

const MusicListItem = ({
    albumName,
    albumCover,
    artistName,
    trackNumber,
    musicName,
    musicCodec,
    isLiked,
    isHated,
    onClick,
    onLongPress
}: MusicListItemProps) => {
    return (
        <div
            className={cx('MusicListItem', { isHated })}
            onClick={onClick}
            onContextMenu={(e) => {
                e.preventDefault();
                onLongPress?.();
            }}>
            {typeof albumCover === 'string' && (
                <Image className={cx('album-art')} src={albumCover} alt={albumName} />
            )}
            <div className={cx('row')}>
                <div className={cx('info', { hasMenu: typeof onLongPress === 'function' })}>
                    <div className={cx('title')}>
                        {!!trackNumber && (
                            <span className={cx('track-number')}>{trackNumber}.</span>
                        )}
                        <span>{musicName}</span>
                        {musicCodec && musicCodec.toLowerCase() === 'flac' && (
                            <span className={cx('codec')}>{musicCodec}</span>
                        )}
                    </div>
                    <div className={cx('artist')}>
                        {artistName}
                    </div>
                </div>
                {onLongPress && (
                    <button
                        className={cx('icon-button', { isLiked })}
                        onClick={(e) => {
                            e.stopPropagation();
                            onLongPress?.();
                        }}>
                        {isLiked ? <Heart /> : <VerticalDots />}
                    </button>
                )}
            </div>
        </div>
    );
};

export default MusicListItem;

// server/src/client/src/components/MusicListItem.svelte
<script lang="ts">
    import Image from "./Image.svelte";
    import Heart from "../icons/Heart.svelte";
    import MoreVerticalFill from "../icons/MoreVerticalFill.svelte";

    export let albumName: string = null;
    export let albumCover: string = null;
    export let artistName: string;
    export let trackNumber: number = null;
    export let musicName: string;
    export let musicCodec: string = null;
    export let isLiked: boolean = false;
    export let onClick: () => void;
    export let onLongPress: () => void = null;
</script>

<button
    class="clickable item"
    on:click={onClick}
    on:contextmenu={(e) => {
        e.preventDefault();
        onLongPress();
    }}
>
    {#if albumCover !== null}
        <Image class="album-art" alt={albumName} src={albumCover} />
    {/if}
    <div class="row">
        <div class="info">
            <div class="title">
                {#if trackNumber !== null}
                    <span class="track-number">
                        {trackNumber}.
                    </span>
                {/if}
                {musicName}
                {#if musicCodec && musicCodec.toLowerCase() === "flac"}
                    <span class="codec">
                        {musicCodec}
                    </span>
                {/if}
            </div>
            <div class="artist">
                <div>
                    {artistName}
                </div>
            </div>
        </div>
        <button
            class="icon-button"
            class:liked={isLiked}
            on:click={(e) => {
                e.stopPropagation();
                onLongPress();
            }}
        >
            {#if isLiked}
                <Heart />
            {:else}
                <MoreVerticalFill />
            {/if}
        </button>
    </div>
</button>

<style lang="scss">
    .row {
        display: flex;
        flex-direction: row;
        align-items: center;
        justify-content: space-between;
        width: 100%;
        gap: 0.5rem;

        .icon-button {
            color: #eee;
            width: 2.5rem;
            height: 2.5rem;

            :global(svg) {
                width: 1.125rem;
                height: 1.125rem;
            }

            &.liked {
                :global(svg) {
                    fill: #a076f1;
                    color: #a076f1;
                }
            }

            @media (hover: hover) {
                &:hover {
                    background-color: rgba(255, 255, 255, 0.1);
                }
            }
        }
    }

    .item {
        color: #eee;
        font-size: 0.8rem;
        cursor: pointer;
        padding: 1rem;
        display: flex;
        flex-direction: row;
        align-items: center;
        gap: 0.5rem;
        width: 100%;

        @media (hover: hover) {
            &:hover {
                background-color: rgba(255, 255, 255, 0.1);
            }
        }

        .artist {
            display: flex;
            align-items: center;
            justify-content: space-between;
            flex-wrap: wrap;
        }

        .title {
            display: flex;
            align-items: center;
            flex-wrap: wrap;
            gap: 0.25rem;

            .track-number {
                font-size: 0.8rem;
                font-weight: 400;
            }

            .codec {
                border: 1px solid #333;
                color: #eee;
                padding: 0.1rem 0.5rem;
                border-radius: 0.5rem;
                font-size: 0.6rem;
                font-weight: 400;
            }
        }
    }
</style>
