// server/src/client/src/pages/Queue.tsx
import styled from '@emotion/styled';
import { useStore } from 'badland-react';
import { useEffect, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import type { HTMLMotionProps } from 'framer-motion';
import { motion } from 'framer-motion';
import { theme } from '@baejino/style';
import { toast } from '@baejino/ui';

import type { DragEndEvent } from '@dnd-kit/core';
import { arrayMove, useSortable } from '@dnd-kit/sortable';
import { CSS } from '@dnd-kit/utilities';

import { VerticalSortable } from '~/components/shared';
import { MusicActionPanelContent, MusicListItem, MusicSelector } from '~/components/music';
import { PlaylistPanelContent } from '~/components/playlist';
import * as Icon from '~/icon';

import { panel } from '~/modules/panel';

import type { Music } from '~/models/type';

import { PlaylistListener } from '~/socket';

import { musicStore } from '~/store/music';
import { queueStore } from '~/store/queue';

const Container = styled.div<HTMLMotionProps<'div'>>`
    display: flex;
    flex-direction: column;
    height: 100%;

    .header {
        display: flex;
        align-items: center;
        justify-content: space-between;
        height: 60px;
        padding: 0 1rem;
        border-bottom: 1px solid #333;

        button {
            width: auto;
            display: flex;
            align-items: center;
            justify-content: center;
            gap: 0.5rem;
            color: #eee;
            font-size: 0.8rem;

            .link {
                width: 0;
                height: 0;
                border-top: 0.3rem solid transparent;
                border-bottom: 0.3rem solid transparent;
                border-left: 0.3rem solid currentColor;
                transform: rotate(90deg);
            }

            &.active {
                color: ${theme.COLOR_PURPLE_PROMINENT};
            }

            svg {
                width: 1rem;
                height: 1rem;
            }
        }
    }

    .footer {
        display: flex;
        align-items: center;
        justify-content: space-between;
        padding: 0.75rem 0.5rem;

        .button {
            border: none;
            background: none;
            color: #a076f1;
            font-size: 1rem;
            font-weight: 600;
            padding: 0.5rem;
            border-radius: 0.5rem;
        }
    }

    .select-actions {
        position: sticky;
        bottom: 0;
        left: 0;
        display: flex;
        align-items: center;
        justify-content: space-between;
        padding: 0.5rem 0;
        background-color: ${theme.COLOR_PURPLE_PROMINENT};

        button {
            display: flex;
            align-items: center;
            flex-direction: column;
            justify-content: center;
            font-size: 0.75rem;
            font-weight: bold;
            gap: 0.25rem;

            svg {
                width: 1.25rem;
                height: 1.25rem;
            }
        }
    }

    ul {
        margin: 0;
        padding: 0;
        width: 100%;
        list-style: none;
    }
`;

const Item = styled.li`
    position: relative;
    display: flex;
    align-items: center;

    .checkbox {
        margin-left: 1rem;

        svg {
            width: 1rem;
            height: 1rem;
        }

        &.active {
            svg {
                color: #ccc;
                fill: ${theme.COLOR_PURPLE_PROMINENT};
            }
        }
    }

    @keyframes breathing {
        0% {
            opacity: 0.15;
        }
        50% {
            opacity: 0.25;
        }
        100% {
            opacity: 0.15;
        }
    }

    &.now-playing {
        &::before {
            content: "";
            position: absolute;
            left: 0;
            top: 0;
            right: 0;
            bottom: 0;
            background-color: #735af2;
            animation: breathing 3s ease infinite;
            z-index: -1;
            pointer-events: none;
        }
    }
`;

const QueueDndItem = ({
    music,
    isCurrentMusic,
    isSelectMode,
    isSelected,
    onSelect,
    onClick,
    onLongPress
}: {
    music: Music;
    isCurrentMusic: boolean;
    isSelectMode: boolean;
    isSelected: boolean;
    onSelect: () => void;
    onClick: () => void;
    onLongPress: () => void;
}) => {
    const {
        attributes, listeners, setNodeRef, transform, transition
    } = useSortable({ id: music.id });
    const style = {
        transform: CSS.Transform.toString(transform),
        transition
    };

    return (
        <Item ref={setNodeRef} {...attributes} style={style} className={isCurrentMusic ? 'now-playing' : ''}>
            {isSelectMode ? (
                <button
                    className={`icon-button checkbox ${isSelected ? 'active' : ''}`}
                    onClick={onSelect}>
                    <Icon.CheckBox />
                </button>
            ) : (
                <button
                    {...listeners}
                    className="icon-button checkbox"
                    style={{
                        cursor: 'grab',
                        touchAction: 'none'
                    }}>
                    <Icon.Menu />
                </button>
            )}
            <div
                style={{
                    flex: 1,
                    maxWidth: 'calc(100% - 4rem)'
                }}>
                <MusicListItem
                    key={music.id}
                    musicName={music.name}
                    artistName={music.artist.name}
                    albumName={music.album.name}
                    albumCover={music.album.cover}
                    isLiked={music.isLiked}
                    isHated={music.isHated}
                    onClick={isSelectMode ? onSelect : onClick}
                    onLongPress={onLongPress}
                />
            </div>
        </Item>
    );
};

export default function Queue() {
    const navigate = useNavigate();

    const [{ items, selected }, setState] = useStore(queueStore);
    const [{ musicMap }] = useStore(musicStore);

    const ref = useRef<HTMLUListElement>(null);
    const [isSelectMode, setIsSelectMode] = useState(false);
    const [selectedItems, setSelectedItems] = useState<string[]>([]);

    const handleDragEnd = async (event: DragEndEvent) => {
        const { active, over } = event;

        if (over) {
            if (active.id === over.id) return;

            setState((prevState) => {
                const prevSelectedItem = prevState.items[prevState.selected!];

                const oldIndex = prevState.items.indexOf(active.id.toString());
                const newIndex = prevState.items.indexOf(over.id.toString());
                const newItems = arrayMove(prevState.items, oldIndex, newIndex);

                if (prevSelectedItem) {
                    return {
                        ...prevState,
                        items: newItems,
                        selected: newItems.indexOf(prevSelectedItem)
                    };
                }

                return {
                    ...prevState,
                    items: newItems
                };
            });
        }
    };

    useEffect(() => {
        setSelectedItems([]);
    }, [isSelectMode]);

    useEffect(() => {
        if (ref.current) {
            const targetElement = ref.current.children.item(
                selected || 0
            ) as HTMLElement;

            if (!targetElement) return;

            ref.current.scrollTo({
                top: targetElement.offsetTop - 60,
                behavior: 'smooth'
            });
        }
    }, [ref, selected]);

    return (
        <Container
            as={motion.div}
            animate="in"
            exit="out"
            initial="out"
            variants={{
                in: {
                    opacity: 1,
                    y: 0
                },
                out: {
                    opacity: 0,
                    y: 50
                }
            }}
            transition={{ duration: 0.25 }}>
            <div className="header">
                <div
                    style={{
                        display: 'flex',
                        alignItems: 'center',
                        gap: '1rem'
                    }}>
                    <MusicSelector
                        label={isSelectMode
                            ? `${selectedItems.length} selected`
                            : `${items?.length} musics`}
                        active={isSelectMode}
                        onClick={() => setIsSelectMode(!isSelectMode)}
                        onSelectAll={() => setSelectedItems(items)}
                    />
                </div>
            </div>
            <ul className="container" ref={ref}>
                <VerticalSortable items={items} onDragEnd={handleDragEnd}>
                    {items?.map((id, idx) => {
                        const music = musicMap.get(id);

                        if (!music) return null;

                        return (
                            <QueueDndItem
                                key={id}
                                music={music}
                                isCurrentMusic={selected === idx}
                                isSelectMode={isSelectMode}
                                isSelected={selectedItems.includes(id)}
                                onSelect={() => {
                                    if (selectedItems.includes(id)) {
                                        setSelectedItems(selectedItems.filter(item => item !== id));
                                    } else {
                                        setSelectedItems([...selectedItems, id]);
                                    }
                                }}
                                onClick={() => {
                                    queueStore.select(idx);
                                }}
                                onLongPress={() => panel.open({
                                    content: (
                                        <MusicActionPanelContent
                                            id={music.id}
                                            onAlbumClick={() => navigate(`/album/${music.album.id}`)}
                                            onArtistClick={() => navigate(`/artist/${music.artist.id}`)}
                                        />
                                    )
                                })}
                            />
                        );
                    })}
                </VerticalSortable>
            </ul>
            {isSelectMode && selectedItems.length > 0 && (
                <div className="select-actions">
                    <button
                        className="clickable"
                        onClick={() => panel.open({
                            title: 'Move to playlist',
                            content: (
                                <PlaylistPanelContent
                                    onClick={(id) => {
                                        PlaylistListener.addMusic(id, selectedItems);
                                        toast('Added to playlist');
                                        setIsSelectMode(false);
                                    }}
                                />
                            )
                        })}>
                        <Icon.Data />
                        <span>Save</span>
                    </button>
                    <button
                        className="clickable"
                        onClick={() => {
                            queueStore.removeItems(selectedItems);
                            setIsSelectMode(false);
                        }}>
                        <Icon.TrashBin />
                        <span>Delete</span>
                    </button>
                </div>
            )}
            <div className="footer">
                <div />
                <button className="icon-button" onClick={() => history.back()}>
                    <Icon.Cross />
                </button>
            </div>
        </Container >
    );
}

// server/src/client/src/components/Queue.svelte
<script lang="ts">
    import { get } from "svelte/store";
    import { navigate } from "svelte-routing";
    import { prompt } from "@baejino/ui";

    import SubPage from "./atom/SubPage.svelte";
    import { Checkbox } from "~/components";
    import MusicListItem from "./MusicListItem.svelte";

    import { Cross, CheckBox, TrashBin, DoubleCheck } from "~/icons";

    import type { Music } from "../models/type";

    import * as socketManager from "../socket";

    import { musicActionPanel, queue } from "../store";

    export let isOpen = false;

    let listRef: HTMLUListElement;
    let enableSelect = false;
    let selectedMusics: Music[] = [];

    $: {
        if (isOpen) {
            setTimeout(() => {
                const targetElement = listRef.children.item(
                    $queue.selected
                ) as HTMLLIElement;
                listRef.scrollTo({
                    top: targetElement.offsetTop - 60,
                    behavior: "smooth",
                });
            }, 100);
        } else {
            enableSelect = false;
            selectedMusics = [];
        }
    }

    const handleClose = () => {
        isOpen = false;
    };

    const handleChangeCheckbox = (music: Music) => {
        if (selectedMusics.find((m) => m.id === music.id)) {
            selectedMusics = selectedMusics.filter((m) => m.id !== music.id);
        } else {
            selectedMusics = [...selectedMusics, music];
        }
    };

    const handleDeleteMusics = () => {
        queue.update((value) => {
            value.items = value.items.filter(
                (m) => !selectedMusics.find((sm) => sm.id === m.id)
            );
            if (value.selected >= value.items.length) {
                value.selected = value.items.length - 1;
            }
            if (value.items.length === 0) {
                value.title = "";
                value.selected = null;
            }
            return value;
        });
        enableSelect = false;
        selectedMusics = [];
    };

    const handleSaveAsPlaylist = async () => {
        const name = await prompt("Input playlist name");

        if (name) {
            socketManager.socket.emit(socketManager.PLAYLIST_CREATE, {
                name,
                musics: get(queue).items.map((m) => m.id),
            });
        }
    };
</script>

<SubPage {isOpen} hasHeader={false}>
    <div class="header">
        <div class="actions">
            <button
                class="clickable"
                class:active={enableSelect}
                on:click={() => {
                    enableSelect = !enableSelect;
                }}
            >
                <CheckBox />
                {$queue.items.length}
                {#if $queue.items.length === 1}music{:else}musics{/if}
            </button>
            {#if enableSelect}
                <button
                    class="clickable"
                    on:click={() => {
                        if (selectedMusics.length === get(queue).items.length) {
                            selectedMusics = [];
                            return;
                        }
                        selectedMusics = get(queue).items;
                    }}
                >
                    <DoubleCheck />
                    Select all
                </button>
            {/if}
        </div>
        {#if !enableSelect}
            <button
                class="clickable title"
                on:click={() => {
                    handleClose();
                    setTimeout(() => {
                        navigate("/queue-history");
                    }, 100);
                }}
            >
                {$queue.title} <span class="link" />
            </button>
        {/if}
    </div>
    <ul class="list" bind:this={listRef}>
        {#each $queue.items as music, idx}
            <li class:active={$queue.selected === idx}>
                {#if enableSelect}
                    <div class="checkbox">
                        <Checkbox
                            checked={selectedMusics.some(
                                (m) => m.id === music.id
                            )}
                            onChange={() => handleChangeCheckbox(music)}
                        />
                    </div>
                {/if}
                <MusicListItem
                    musicName={music.name}
                    artistName={music.artist.name}
                    albumName={music.album.name}
                    albumCover={music.album.cover}
                    musicCodec={music.codec}
                    isLiked={music.isLiked}
                    onClick={() => {
                        if (enableSelect) {
                            handleChangeCheckbox(music);
                            return;
                        }
                        queue.update((value) => {
                            value.selected = idx;
                            return value;
                        });
                    }}
                    onLongPress={() => {
                        musicActionPanel.update((state) => ({
                            ...state,
                            onPageMove: () => (isOpen = false),
                            isOpen: true,
                            music,
                        }));
                    }}
                />
            </li>
        {/each}
    </ul>
    {#if enableSelect && selectedMusics.length > 0}
        <div class="select-actions">
            <button class="clickable" on:click={handleDeleteMusics}>
                <TrashBin />
                Delete
            </button>
        </div>
    {/if}
    <div class="action">
        <div class="buttons">
            <button class="button" on:click={handleSaveAsPlaylist}>
                Save as
            </button>
        </div>
        <button class="icon-button" on:click={handleClose}>
            <Cross />
        </button>
    </div>
</SubPage>

<style lang="scss">
    @import "../styles/var.scss";

    .list {
        flex: 1;
        overflow-y: auto;
    }

    .header {
        display: flex;
        align-items: center;
        justify-content: space-between;
        height: 60px;
        padding: 0 1rem;
        border-bottom: 1px solid #333;

        .actions {
            display: flex;
            align-items: center;
            gap: 1rem;
        }

        button {
            width: auto;
            display: flex;
            align-items: center;
            justify-content: center;
            gap: 0.5rem;
            color: #eee;
            font-size: 0.8rem;

            .link {
                width: 0;
                height: 0;
                border-top: 0.3rem solid transparent;
                border-bottom: 0.3rem solid transparent;
                border-left: 0.3rem solid currentColor;
                transform: rotate(90deg);
            }

            &.active {
                color: $PRIMARY_COLOR;
            }

            :global(svg) {
                width: 1rem;
                height: 1rem;
            }
        }
    }

    .action {
        display: flex;
        align-items: center;
        justify-content: space-between;
        padding: 0.5rem;

        .buttons {
            display: flex;
            align-items: center;
            gap: 0.5rem;
        }

        .button {
            border: none;
            background: none;
            color: #a076f1;
            font-size: 1rem;
            font-weight: 600;
            padding: 0.5rem;
            border-radius: 0.5rem;
        }
    }

    .select-actions {
        position: sticky;
        bottom: 0;
        left: 0;
        display: flex;
        align-items: center;
        justify-content: space-between;
        padding: 0.5rem 0;
        background-color: $PRIMARY_COLOR;

        button {
            display: flex;
            align-items: center;
            flex-direction: column;
            justify-content: center;
            font-size: 0.75rem;
            font-weight: bold;
            gap: 0.25rem;

            :global(svg) {
                width: 1.25rem;
                height: 1.25rem;
            }
        }
    }

    ul {
        margin: 0;
        padding: 0;
        width: 100%;
        list-style: none;

        li {
            position: relative;
            display: flex;
            align-items: center;

            .checkbox {
                margin-left: 1rem;
            }

            @keyframes breathing {
                0% {
                    opacity: 0.15;
                }
                50% {
                    opacity: 0.25;
                }
                100% {
                    opacity: 0.15;
                }
            }

            &.active {
                &::before {
                    content: "";
                    position: absolute;
                    left: 0;
                    top: 0;
                    right: 0;
                    bottom: 0;
                    background-color: #735af2;
                    animation: breathing 3s ease infinite;
                    z-index: -1;
                    pointer-events: none;
                }
            }
        }
    }
</style>
